/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "net_piclock_nativeImpl_Tm1637.h"
#include <stdbool.h> 

#include "TM1637.h"  //https://stackoverflow.com/questions/16850992/call-a-c-function-from-c-code
#include <stdio.h>

//#define clk 4//pins definitions for TM1637 and can be changed to other ports    
//#define dio 5


 bool isPointActive = false;

/*
 * Class:     net_piclock_nativeImpl_Tm1637
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT jint JNICALL Java_net_piclock_nativeImpl_Tm1637_init
  (JNIEnv* env, jobject obj, jint clk, jint dio){
  
  	 if(wiringPiSetup()==-1) {
    	 printf("setup wiringPi failed!");
     return 1;
  	}

  	pinMode((int)clk,INPUT);
  	pinMode((int)dio,INPUT);
  	delay(200);
  	TM1637_init((int)clk,(int)dio);
  	TM1637_set(BRIGHT_TYPICAL,0x40,0xc0);//BRIGHT_TYPICAL = 2,BRIGHT_DARKEST = 0,BRIGHTEST = 7;
  	  
  	return 0;
  }

/*
 * Class:     net_piclock_nativeImpl_Tm1637
 * Method:    displayTime
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_piclock_nativeImpl_Tm1637_displayTime
  (JNIEnv* env, jobject obj, jint hour, jint min, jint format){
  
    if (!isPointActive){
  	TM1637_point(POINT_ON);
  	isPointActive = true;
  }
  
  
  
  	if (format == 0 || format > 1){ //12 hours format
  		if (hour == 0) {
		  TM1637_display(0,1);
		  TM1637_display(1,2);
		} else if (hour > 21) {
		  TM1637_display(0,1);
		  TM1637_display(1,hour - 22);
		} else if (hour > 12) {
		  TM1637_display(0,0x7f);
		  TM1637_display(1,hour - 12);
		} else if (hour > 9) {
		  TM1637_display(0,1);
		  TM1637_display(1,hour - 10);
		} else {
		  TM1637_display(0,0x7f);
		  TM1637_display(1,hour);
		}  	
  	}else {
  		//24 hours format
  		TM1637_display(0,hour/10);
		TM1637_display(1,hour % 10);
  	}
  	
  	/* minutes */
		int min1 = min/10;
		int min2 = min % 10;
		TM1637_display(2,min1);
		TM1637_display(3,min2);
  
  }
/*
 * Class:     net_piclock_nativeImpl_Tm1637
 * Method:    clearDisplay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_piclock_nativeImpl_Tm1637_clearDisplay
  (JNIEnv* env, jobject obj){
  	TM1637_clearDisplay();
  }
/*
 * Class:     net_piclock_nativeImpl_Tm1637
 * Method:    displayNumberPos
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_piclock_nativeImpl_Tm1637_displayNumberPos
  (JNIEnv* env, jobject obj, jint nbr, jint position){
  	TM1637_display(position,nbr);
  }
/*
 * Class:     net_piclock_nativeImpl_Tm1637
 * Method:    displayPoint
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_piclock_nativeImpl_Tm1637_displayPoint
  (JNIEnv* env, jobject obj, jboolean pointOn){
  
 
  
  	if (pointOn && !isPointActive){
  		TM1637_point(POINT_ON);
  		isPointActive = true;
  	}else if (!pointOn && isPointActive){
  		TM1637_point(POINT_OFF);
  		isPointActive = false;
  	}
 
  }
/*
 * Class:     net_piclock_nativeImpl_Tm1637
 * Method:    setBrightness
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_piclock_nativeImpl_Tm1637_setBrightness
  (JNIEnv* env, jobject obj, jint level){
  	//from level 0 to 7
  	
  	if (level > 7){
  		TM1637_set(BRIGHTEST,0x40,0xc0);
  	}else if (level < 0){
  		TM1637_set(BRIGHT_DARKEST,0x40,0xc0);
  	}else{
  		TM1637_set((int)level,0x40,0xc0);
  	 }
  }


