/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_piclock_nativeImpl_Tm1637 */

#ifndef _Included_net_piclock_nativeImpl_Tm1637
#define _Included_net_piclock_nativeImpl_Tm1637
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_piclock_nativeImpl_Tm1637
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT jint JNICALL Java_net_piclock_nativeImpl_Tm1637_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_piclock_nativeImpl_Tm1637
 * Method:    displayTime
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_piclock_nativeImpl_Tm1637_displayTime
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     net_piclock_nativeImpl_Tm1637
 * Method:    clearDisplay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_piclock_nativeImpl_Tm1637_clearDisplay
  (JNIEnv *, jobject);

/*
 * Class:     net_piclock_nativeImpl_Tm1637
 * Method:    displayNumberPos
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_piclock_nativeImpl_Tm1637_displayNumberPos
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_piclock_nativeImpl_Tm1637
 * Method:    displayPoint
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_piclock_nativeImpl_Tm1637_displayPoint
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     net_piclock_nativeImpl_Tm1637
 * Method:    setBrightness
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_piclock_nativeImpl_Tm1637_setBrightness
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
