package net.piclock.enums;

public enum LabelEnums {
	CURRENT_WEATHER, TEMP_SUN, TEMP_SHADE, CLOCK, DAY_OF_WEEK,WTH_LST_UPD_TIME,
	ALARM_TITLE, ALARM_HOUR, ALARM_MIN, ALARM_HOUR_TXT, ALARM_MIN_TXT,
	ALARM_SUNDAY, ALARM_MON, ALARM_TU, ALARM_WED, ALARM_TH, ALARM_FRI, ALARM_SAT,
	WC_TITILE,WC_ACTIVATE,WC_PROVIDER,WC_CITY,WC_REFRESH,WC_MIN,
	WC_ALERT_TITLE, WC_ALERT_TEXT,WEATHER_FORECAST_VIEW,
	CFG_TITLE, CFG_WIFI_NAME, CFG_WIFI_PASS, CFG_WIFI_CHKBX,CFG_SCREEN_CHKBX,
	RADIO_NOW_PLAYING, RADIO_TITLE, RADIO_STATIONS, RADIO_SLEEP, WSERVER_TITLE,
	WSERVER_ADDRESS,WSERVER_STATUS,WSERVER_ADDRESS_TXT; 
}